prompts:
  packages:
    prompt: What packages should this charm install (space seperated list)?
    default: 'congress-server congress-common python-antlr3 python-pymysql'
    type: string
  release:
    prompt: What is the earliest OpenStack release this charm will support?
    default: 'mitaka'
    type: string
  api_service:
    prompt: What is the name of the api service?
    default: 'congress-server'
    type: string
  service_init:
    prompt: Provide a space sperated list of the services this charm provides
    default: 'congress-server'
    type: string
  service_port:
    prompt: What port does the api service listen on ?
    default: '1789'
    type: string
  service_name:
    prompt: What name should be used for this service in the keystone catalogue?
    default: 'congress'
    type: string
  service_confs:
    prompt: List of config files managed by this charm (space seperated)
    default: '/etc/congress/congress.conf'
    type: string
  db_sync_command:
    prompt: What command is used to sync the database (If multiple are needed provide a comma seperated list)?
    default: 'congress-db-manage --config-file /etc/congress/congress.conf upgrade head'
    type: string
